---
output: github_document
params:
  dataset: "http://bit.ly/mtcars_tsv"
  groups: !r c("species")
  axes: !r c("sepal_length", "sepal_width")
  facets: !r NULL
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
# Analyze a dataset: Clean it and summarize and plot the mean values of numeric
# variebles, optionally by groups.

# Setup -------------------------------------------------------------------

r_path <- function(...) here::here(...)
source(r_path("01_packages.R"))
source(r_path("02_functions.R"))

# Parameters --------------------------------------------------------------

(dataset <- params$dataset)
(groups <- params$groups)
(axes <- params$axes)
(facets <- params$facets)

# Data --------------------------------------------------------------------

(raw <- vroom(dataset, col_types = cols()))

# Analysis ----------------------------------------------------------------

(prep <- raw %>% prepare())

(means <- prep %>% mean_of_numerics(groups))

means %>% plot_xy(axes, by = facets)

```

